// ﻿// <auto-generated />
// using System;
// using Microsoft.EntityFrameworkCore;
// using Microsoft.EntityFrameworkCore.Infrastructure;
// using Microsoft.EntityFrameworkCore.Metadata;
// using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
// using NEXTGroup3.Data;

// #nullable disable

// namespace NEXTGroup3.Migrations
// {
//     [DbContext(typeof(AzureContext))]
//     partial class AzureContextModelSnapshot : ModelSnapshot
//     {
//         protected override void BuildModel(ModelBuilder modelBuilder)
//         {
// #pragma warning disable 612, 618
//             modelBuilder
//                 .HasAnnotation("ProductVersion", "8.0.11")
//                 .HasAnnotation("Relational:MaxIdentifierLength", 128);

//             SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
//                 {
//                     b.Property<string>("Id")
//                         .HasColumnType("nvarchar(450)");

//                     b.Property<string>("ConcurrencyStamp")
//                         .IsConcurrencyToken()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("Name")
//                         .HasMaxLength(256)
//                         .HasColumnType("nvarchar(256)");

//                     b.Property<string>("NormalizedName")
//                         .HasMaxLength(256)
//                         .HasColumnType("nvarchar(256)");

//                     b.HasKey("Id");

//                     b.HasIndex("NormalizedName")
//                         .IsUnique()
//                         .HasDatabaseName("RoleNameIndex")
//                         .HasFilter("[NormalizedName] IS NOT NULL");

//                     b.ToTable("AspNetRoles", (string)null);
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                     b.Property<string>("ClaimType")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("ClaimValue")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("RoleId")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(450)");

//                     b.HasKey("Id");

//                     b.HasIndex("RoleId");

//                     b.ToTable("AspNetRoleClaims", (string)null);
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                     b.Property<string>("ClaimType")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("ClaimValue")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("UserId")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(450)");

//                     b.HasKey("Id");

// <<<<<<< login-system
//                     b.HasIndex("UserId");

//                     b.ToTable("AspNetUserClaims", (string)null);
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
//                 {
//                     b.Property<string>("LoginProvider")
//                         .HasColumnType("nvarchar(450)");

//                     b.Property<string>("ProviderKey")
//                         .HasColumnType("nvarchar(450)");

//                     b.Property<string>("ProviderDisplayName")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("UserId")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(450)");

//                     b.HasKey("LoginProvider", "ProviderKey");

//                     b.HasIndex("UserId");

//                     b.ToTable("AspNetUserLogins", (string)null);
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
//                 {
//                     b.Property<string>("UserId")
//                         .HasColumnType("nvarchar(450)");

//                     b.Property<string>("RoleId")
//                         .HasColumnType("nvarchar(450)");

//                     b.HasKey("UserId", "RoleId");

//                     b.HasIndex("RoleId");

//                     b.ToTable("AspNetUserRoles", (string)null);
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
//                 {
//                     b.Property<string>("UserId")
//                         .HasColumnType("nvarchar(450)");

//                     b.Property<string>("LoginProvider")
//                         .HasColumnType("nvarchar(450)");

//                     b.Property<string>("Name")
//                         .HasColumnType("nvarchar(450)");

//                     b.Property<string>("Value")
//                         .HasColumnType("nvarchar(max)");

//                     b.HasKey("UserId", "LoginProvider", "Name");

//                     b.ToTable("AspNetUserTokens", (string)null);
// =======
//                     b.ToTable("Candidate");
// >>>>>>> dev
//                 });

//             modelBuilder.Entity("NEXTGroup3.Models.Department", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                     b.Property<string>("Description")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("Link")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("Name")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<int?>("RangeQuestionId")
//                         .HasColumnType("int");

//                     b.Property<int?>("RangeQuestionId1")
//                         .HasColumnType("int");

//                     b.HasKey("Id");

//                     b.HasIndex("RangeQuestionId");

//                     b.HasIndex("RangeQuestionId1");

//                     b.ToTable("Department");
// <<<<<<< login-system
//                 });

//             modelBuilder.Entity("NEXTGroup3.Models.NextUser", b =>
//                 {
//                     b.Property<string>("Id")
//                         .HasColumnType("nvarchar(450)");

//                     b.Property<int>("AccessFailedCount")
//                         .HasColumnType("int");

//                     b.Property<string>("ConcurrencyStamp")
//                         .IsConcurrencyToken()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("Email")
//                         .HasMaxLength(256)
//                         .HasColumnType("nvarchar(256)");

//                     b.Property<bool>("EmailConfirmed")
//                         .HasColumnType("bit");

//                     b.Property<string>("FirstName")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("LastName")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<bool>("LockoutEnabled")
//                         .HasColumnType("bit");

//                     b.Property<DateTimeOffset?>("LockoutEnd")
//                         .HasColumnType("datetimeoffset");

//                     b.Property<string>("NormalizedEmail")
//                         .HasMaxLength(256)
//                         .HasColumnType("nvarchar(256)");

//                     b.Property<string>("NormalizedUserName")
//                         .HasMaxLength(256)
//                         .HasColumnType("nvarchar(256)");

//                     b.Property<string>("PasswordHash")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("PhoneNumber")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<bool>("PhoneNumberConfirmed")
//                         .HasColumnType("bit");

//                     b.Property<string>("SecurityStamp")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<bool>("TwoFactorEnabled")
//                         .HasColumnType("bit");

//                     b.Property<string>("UserName")
//                         .HasMaxLength(256)
//                         .HasColumnType("nvarchar(256)");

//                     b.HasKey("Id");

//                     b.HasIndex("NormalizedEmail")
//                         .HasDatabaseName("EmailIndex");

//                     b.HasIndex("NormalizedUserName")
//                         .IsUnique()
//                         .HasDatabaseName("UserNameIndex")
//                         .HasFilter("[NormalizedUserName] IS NOT NULL");

//                     b.ToTable("AspNetUsers", (string)null);
// =======
// >>>>>>> dev
//                 });

//             modelBuilder.Entity("NEXTGroup3.Models.DepartmentRangeQuestion", b =>
//                 {
//                     b.Property<bool>("Alignment")
//                         .HasColumnType("bit");

//                     b.Property<int>("DepartmentId")
//                         .HasColumnType("int");

//                     b.Property<int>("RangeQuestionId")
//                         .HasColumnType("int");

//                     b.ToTable("DepartmentRangeQuestion");
//                 });

//             modelBuilder.Entity("NEXTGroup3.Models.EncouragingMessage", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                     b.Property<string>("Message")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.HasKey("Id");

// <<<<<<< login-system
//                     b.ToTable("RangeQuestion");
// =======
//                     b.ToTable("EncouragingMessage");
// >>>>>>> dev
//                 });

//             modelBuilder.Entity("NEXTGroup3.Models.RangeQuestion", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                     b.Property<string>("QuestionText")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.HasKey("Id");

// <<<<<<< login-system
//                     b.ToTable("Result");
// =======
//                     b.ToTable("RangeQuestion");
// >>>>>>> dev
//                 });

//             modelBuilder.Entity("NEXTGroup3.Models.Result", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

// <<<<<<< login-system
//                     b.Property<int>("DepartmentId")
// =======
//                     b.Property<int?>("CandidateId")
// >>>>>>> dev
//                         .HasColumnType("int");

//                     b.Property<string>("DepartmentPoints")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("RolePoints")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

// <<<<<<< login-system
//                     b.HasKey("Id");

//                     b.ToTable("Role");
//                 });

//             modelBuilder.Entity("NEXTGroup3.Models.TextAnswer", b =>
// =======
//                     b.Property<DateTime>("Timestamp")
//                         .HasColumnType("datetime2");

//                     b.HasKey("Id");

//                     b.ToTable("Result");
//                 });

//             modelBuilder.Entity("NEXTGroup3.Models.Role", b =>
// >>>>>>> dev
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                     b.Property<string>("Answers")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<int>("RoleId")
//                         .HasColumnType("int");

//                     b.Property<string>("Link")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("Name")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

// <<<<<<< login-system
//                     b.HasIndex("RoleId");

//                     b.ToTable("TextAnswer");
// =======
//                     b.HasKey("Id");

//                     b.ToTable("Role");
// >>>>>>> dev
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
//                 {
//                     b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
//                         .WithMany()
//                         .HasForeignKey("RoleId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
//                 {
//                     b.HasOne("NEXTGroup3.Models.NextUser", null)
//                         .WithMany()
//                         .HasForeignKey("UserId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
//                 {
//                     b.HasOne("NEXTGroup3.Models.NextUser", null)
//                         .WithMany()
//                         .HasForeignKey("UserId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//                 });

//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
//                 {
//                     b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
//                         .WithMany()
//                         .HasForeignKey("RoleId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.HasOne("NEXTGroup3.Models.NextUser", null)
//                         .WithMany()
//                         .HasForeignKey("UserId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
//                 });

// <<<<<<< login-system
//             modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
//                 {
//                     b.HasOne("NEXTGroup3.Models.NextUser", null)
//                         .WithMany()
//                         .HasForeignKey("UserId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();
// =======
//                     b.ToTable("Staff");
//                 });

//             modelBuilder.Entity("NEXTGroup3.Models.TextAnswer", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                     b.Property<string>("Answers")
//                         .IsRequired()
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<int>("RoleId")
//                         .HasColumnType("int");

//                     b.HasKey("Id");

//                     b.HasIndex("RoleId");

//                     b.ToTable("TextAnswer");
// >>>>>>> dev
//                 });

//             modelBuilder.Entity("NEXTGroup3.Models.Department", b =>
//                 {
//                     b.HasOne("NEXTGroup3.Models.RangeQuestion", null)
//                         .WithMany("LeftDepartments")
//                         .HasForeignKey("RangeQuestionId");

//                     b.HasOne("NEXTGroup3.Models.RangeQuestion", null)
//                         .WithMany("RightDepartments")
//                         .HasForeignKey("RangeQuestionId1");
//                 });

//             modelBuilder.Entity("NEXTGroup3.Models.TextAnswer", b =>
//                 {
//                     b.HasOne("NEXTGroup3.Models.Role", "Role")
//                         .WithMany()
//                         .HasForeignKey("RoleId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.Navigation("Role");
//                 });

//             modelBuilder.Entity("NEXTGroup3.Models.RangeQuestion", b =>
//                 {
//                     b.Navigation("LeftDepartments");

//                     b.Navigation("RightDepartments");
//                 });
// #pragma warning restore 612, 618
//         }
//     }
// }
